pub: remove spin due to build error
$ spin build
Building component spingo with `tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go`
# golang.org/x/sys/unix
../../../../go/pkg/mod/golang.org/x/sys@v0.16.0/unix/syscall_linux.go:1901:64: undefined: syscall.Rlimit
../../../../go/pkg/mod/golang.org/x/sys@v0.16.0/unix/syscall_linux.go:1906:50: undefined: syscall.Rlimit
../../../../go/pkg/mod/golang.org/x/sys@v0.16.0/unix/syscall_linux.go:1906:79: undefined: syscall.Rlimit
../../../../go/pkg/mod/golang.org/x/sys@v0.16.0/unix/syscall_unix.go:605:17: undefined: syscall.Setrlimit
../../../../go/pkg/mod/golang.org/x/sys@v0.16.0/unix/syscall_unix.go:605:47: undefined: syscall.Rlimit
Error: Build command for component spingo failed with status Exited(1)